ParcInfo/urls.py
from django.urls import include, path
from django.contrib import admin


from django.conf.urls.static import static
from django.conf import settings




urlpatterns = [
    path('parc/', include('parc.urls')),
    path('blog/', include('blog.urls')),
    
    path('userprofile/', include('userprofile.urls')),
    path('intervention/', include('intervention.urls')),
    path('service/', include('service.urls')),

    path('admin/', admin.site.urls),
]

blog/urls.py
from django.urls import path


from . import views as blog

app_name="blog"
urlpatterns = [
    path('index', blog.index, name='index'),
    path('contact', blog.contact, name='contact'),
    path('accueil', blog.accueil, name='accueil'),
    path('accueill', blog.accueill, name='accueill'),
    path('forum', blog.forum, name='forum'),
    path('signup', blog.signup, name='signup'),
    path('signin', blog.signin, name='signin'),
    path('register', blog.register, name='register'),
    path('dashboard', blog.dashboard, name='dashboard'),
    path('login', blog.login, name='login'),
    path('logout', blog.logout, name='logout'),
    path('lock', blog.lock, name='lock'),
    path('inscription', blog.inscription, name='inscription'),
    path('email_detail', blog.email_detail, name='email_detail'),
    #path('contactview', blog.contactview, name='contactview'),
    
    path('listservice', blog.listservice, name='listservice'),
    path('listparc', blog.listparc, name='listparc'),
    path('listintervention', blog.listintervention, name='listintervention'),
    
    path('add_email', blog.add_email, name='add_email'),
    path('generalchat', blog.generalchat, name='generalchat'),
    path('post', blog.post, name='post'),
    path('uploads', blog.uploads, name='uploads'),
  
  
    #path('successview/', blog.successview, name='successview'),
    
    ]

service/urls.py
from django.urls import path

from . import views as service

app_name="service"
urlpatterns = [
         
         path('bureau', service.bureau, name='bureau'), 
         path('bureau_detail', service.bureau_detail, name='bureau_detail'), 
         path('add_bureau', service.add_bureau, name='add_bureau'),   
         path('oneburo/<int:id>', service.oneburo, name='oneburo'), 
         path('updateburo/<int:id>', service.updateburo, name='updateburo'),
         path('oneburodel/<int:id>', service.oneburodel, name='oneburodel'), 
         path('deleteburo/<int:id>', service.deleteburo, name='deleteburo'), 
         
        
         
         path('departement', service.departement, name='departement'),
         path('departement_detail', service.departement_detail, name='departement_detail'),      
         path('add_departement', service.add_departement, name='add_departement'), 
         path('onedep/<int:id>', service.onedep, name='onedep'), 
         path('updatedep/<int:id>', service.updatedep, name='updatedep'), 
         path('onedepdelete/<int:id>', service.onedepdelete, name='onedepdelete'), 
         path('deletedep/<int:id>', service.deletedep, name='deletedep'), 
         
         
         path('oneinterv/<int:id>', service.oneinterv, name='oneinterv'), 
         path('updateinterv/<int:id>', service.updateinterv, name='updateinterv'),
         path('oneintervdelete/<int:id>', service.oneintervdelete, name='oneintervdelete'), 
         path('deleteinterv/<int:id>', service.deleteinterv, name='deleteinterv'), 
         path('add_intervenant', service.add_intervenant, name='add_intervenant'),   
         path('intervenant', service.intervenant, name='intervenant'),
         path('intervenant_detail', service.intervenant_detail, name='intervenant_detail'),
         path('page', service.page, name='page'), 
        
]

service/models.py
from django.db import models
from django.utils.translation import gettext as _


# Create your models here.


# LIBELLE_DEPARTEMENT= (
#     ('COMPTABILITE', 'COMPTABILITE'),
#     ('COMMUNICATION', 'COMMUNICATION'),
#     ('INFORMATIQUE', 'INFORMATIQUE'),
#     ('MARKETING', 'MARKETING'),
#     ('RESEAUX', 'RESEAUX'),
    
# ) 


class Departement(models.Model):
    libelle_dep = models.CharField("Libelle du departement", max_length=100, blank=True, null=True)
    description = models.CharField("Description du Departement",max_length=100, blank=True, null=True)
    
    
    class Meta:
        verbose_name = _("Departement")
        verbose_name_plural = _("Departements")
        
    def __str__(self):
        return '%s' % self.libelle_dep

    def get_absolute_url(self):
        return reverse("departement_detail",kwargs={"pk": self.pk})
    


class Bureau(models.Model):
    num_bureau = models.IntegerField(("numéro du Bureau"), blank=True, null=True)
    departement = models.ForeignKey(Departement, related_name='departement', on_delete=models.CASCADE, blank=True, null=True)
    
    
    class Meta:
        verbose_name = _("Bureau")
        verbose_name_plural = _("Bureaux")
        
    def __str__(self):
        return '%s' % self.num_bureau

    def get_absolute_url(self):
        return reverse("bureau_detail",kwargs={"pk": self.pk})
    



class Intervenant(models.Model):
    nom_intervenant =  models.CharField("nom de l'intervenant", max_length=100, blank=True, null=True )
    telephone = models.CharField("telephone", max_length=11, blank=True, null=True)
    email= models.EmailField(_("couriel"), blank=True, null=True)
    

    class Meta:
        verbose_name = _("Intervenant")
        verbose_name_plural = _("Intervenants")

    def __str__(self):
        return  self.nom_intervenant

    def get_absolute_url(self):
        return reverse("intervenant_detail", kwargs={"pk": self.pk})

        

service/forms.py
from django.forms import ModelForm, Textarea
from django import forms
from .models import Departement, Bureau, Intervenant


class DepartementForm(ModelForm):
    class Meta:
        model = Departement
        fields = ('libelle_dep', 'description')
    
    # def clean_libelle_dep(self):
    #       libelle_dep = self.cleaned_data['libelle_dep']
    #       if self.instance.id:
    #          if Departement.objects.filter(libelle_dep=libelle_dep).exclude(id=self.instance.id):
    #             raise forms.ValidationError(
    #                         'Menu with this title already exists.')
    #          else:
    #             if Departement.objects.filter(libelle_dep=libelle_dep):
    #                raise forms.ValidationError(
    #                         'Menu with this subject already exists.')
    #             return libelle_dep

    # def clean_description(self):
    #       description = self.cleaned_data['description']
    #       if len(description) > 80:
    #          raise forms.ValidationError(
    #                         'content should not exceed 80 characters')
    #       return description
       

        

class BureauForm(ModelForm):
    num_bureau = forms.IntegerField()
    departement = forms.ModelChoiceField(queryset=Departement.objects.all(), initial=0)
    class Meta:
        model = Bureau
        fields = ('num_bureau', 'departement')
        
        
        
        
    # def __init__(self, *args, **kwargs):
    #     super().__init__(*args, **kwargs)
    #     self.fields['departement'].queryset = Departement.objects.none()

    #     if 'departement' in self.data:
    #         try:
                
    #           departement_id = int(self.data.get('departement'))
    #           self.fields['departement'].queryset = Departement.objects.filter(departement_id=departement_id).order_by('name')
    #         except (ValueError, TypeError):
    #             pass  # invalid input from the client; ignore and fallback to empty City queryset
    #     elif self.instance.pk:
    #         self.fields['departement'].queryset = self.instance.departement.departement_set.order_by('name')
        
 

class IntervenantForm(ModelForm):
    class Meta:
        model = Intervenant
        fields = ('nom_intervenant', 'telephone', 'email')
       
            

service/views.py
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import render, get_object_or_404, redirect
from .forms import IntervenantForm, DepartementForm, BureauForm, forms
from .models import Bureau, Departement, Intervenant
from django.http import HttpResponse, HttpResponseRedirect,JsonResponse

# Create your views here.

def departement (request):
    return render(request, 'service/Departement.html')
        #==============================View de detail===============================

def departement_detail(request):
    departement= Departement.objects.all()
    
    return render(request, 'service/Departement_detail.html', {'departement':departement})

        #====================================La view form departemet================
def add_departement (request):   
    departement= Departement.objects.all()
    if request.method == 'POST':
        departement= Departement(
            libelle_dep = request.POST.get("libelle_dep"),
            description = request.POST.get("description"),            
        )
        departement.save()
        return HttpResponseRedirect('departement_detail')
    else:
        message ="Echec"
    return render(request,'service/Departement.html',{'departement':departement})


def onedep(request, id):
    departement = Departement.objects.get(pk=id)
    return render(request, "service/Updatedep.html", {'departement':departement})

def updatedep(request, id):
    departement = Departement.objects.get(pk=id)
    if request.method == 'POST':
        departement= Departement(
            id=id,           
            libelle_dep = request.POST.get("libelle_dep"),
            description = request.POST.get("description"),            
        )
        departement.save()
        return HttpResponseRedirect('/service/departement_detail')
    
def onedepdelete(request, id):
    departement = Departement.objects.get(pk=id)
    return render(request, "service/deletedep.html", {'departement':departement})

def deletedep(request,id):
    departement = Departement.objects.get(pk=id)
    departement.delete()
    return HttpResponseRedirect('/service/departement_detail')
    


#======================================view de bureau=======================================================

def bureau (request):
    departements = Departement.objects.all()
    
    #departement.pk = None
    return render(request, 'service/Bureau.html',{'departements':departements})
   
       #============================= View de deteil bureau ===========================

def bureau_detail (request):
    departements = Departement.objects.all()
    bureau  = Bureau.objects.all()
    print(bureau)
    
    return render(request, 'service/Bureau_detail.html', {'bureau':bureau})




       
       #============================= View form de  bureau ===========================
def add_bureau (request):
    bureau= Bureau.objects.all()
    departement = Departement.objects.get(libelle_dep=request.POST.get("departement"))
    if request.method == 'POST':
        bureau= Bureau(
            num_bureau = request.POST.get("num_bureau"),
            departement = departement,
                      
        )
        bureau.save()
       # mssage =  "% Bureau added succesfully"
        return HttpResponseRedirect('bureau_detail')
    else:
        mssage ="Echec"
    return render(request,'service/Bureau.html',{'bureau':bureau})

      #============================= View Update et Delete de  bureau ===================
      
def oneburo(request, id):
    bureau  = Bureau.objects.get(pk=id)
    departement = Departement.objects.all()
    
    return render(request, 'service/Updateburo.html', {'bureau':bureau, 'departement':departement})

def updateburo(request, id):
    bureau  = Bureau.objects.get(pk=id)
    departement = Departement.objects.get(libelle_dep=request.POST.get("departement"))
    if request.method == 'POST':
        bureau= Bureau(
            id=id,
            num_bureau = request.POST.get("num_bureau"),
            departement = departement,
                      
        )
        bureau.save()
       # mssage =  "% Bureau added succesfully"
        return HttpResponseRedirect('/service/bureau_detail')


def oneburodel(request, id):
    bureau  = Bureau.objects.get(pk=id)
    departement = Departement.objects.all()
    
    return render(request, 'service/Deleteburo.html', {'bureau':bureau, 'departement':departement})


def deleteburo(request, id):
    bureau  = Bureau.objects.get(pk=id)
    bureau.delete()
    return HttpResponseRedirect('/service/bureau_detail')
    

    

   

#=======================================La view form d'intervenant==========================================
def add_intervenant (request):
    intervenant= Intervenant.objects.all()
    if request.method == 'POST':
        intervenant = Intervenant(
            nom_intervenant = request.POST.get("nom_intervenant"),
            telephone = request.POST.get("telephone"),
            email = request.POST.get("email"),           
        )
        intervenant.save()
        return HttpResponseRedirect('intervenant_detail')
    else:
        mssage ="Echec"
    return render(request,'service/Intervenant.html',{'intervenant':intervenant})

    #=================================Le view d'intervenant==================================
def intervenant (request):
    
    
    return render(request, 'service/Intervenant.html')

    #=================================Le view detail intervenant==================================
def intervenant_detail (request):
    intervenant  = Intervenant.objects.all()
    
    
    return render(request, 'service/Intervenant_detail.html', {'intervenant':intervenant})

    #=================================Le view Udate et Delete intervenant==================================

def oneinterv(request, id):
    intervenant  = Intervenant.objects.get(pk=id)
    
    return render(request, 'service/Updateinterv.html', {'intervenant':intervenant})


def updateinterv(request, id):
    intervenant  = Intervenant.objects.get(pk=id)
    if request.method == 'POST':
        intervenant = Intervenant(
            id=id,
            nom_intervenant = request.POST.get("nom_intervenant"),
            telephone = request.POST.get("telephone"),
            email = request.POST.get("email"),           
        )
        intervenant.save()
        return HttpResponseRedirect('/service/intervenant_detail')
    

def oneintervdelete(request, id):    
    intervenant  = Intervenant.objects.get(pk=id)
    
    return render(request, 'service/Deleteinterv.html', {'intervenant':intervenant})

def deleteinterv(request,id):
    intervenant  = Intervenant.objects.get(pk=id)
    intervenant.delete()
    return HttpResponseRedirect('/service/intervenant_detail')
    





#==========================================END INTERVENANT =================================================

def page(request):
    return render(request, 'service/page.html')

templates/service/Bureau.html
{% extends "base1.html" %}{% load staticfiles %} {% block title %}
<title>Bureau</title>{% endblock title %}{% block content %}
<div class="container">


    <div class="right_col" role="main">
        <div class="">

            <div class="clearfix"></div>
            <div class="row">
                <div class="col-md-12 col-sm-12 ">
                    <div class="x_panel">

                        <div class="x_content">
                            <br />
                            <form id="demo-form2" data-parsley-validate class="form-horizontal form-label-left" method="POST" action="{%url 'service:add_bureau' %}">
                                {%csrf_token%}
                                <div class="page-header ">
                                    <h3>Enregistrement de Bureau</h3>
                                </div>

                                <div class="form-group row ">
                                    <label class="control-label col-md-3 col-sm-3 " for="first-name ">Numero du Bureau: <span class="required ">*</span>
                                    </label>
                                    <div class="col-md-4 col-sm-4 ">
                                        <input type="number" class="form-control" id="num_bureau" name="num_bureau" rows="1">
                                    </div>
                                    <span class="tooltip ">Un nom ne peut pas faire moins de 2 caractères</span>
                                </div>

                                <div class="form-group row ">
                                    <label class="control-label col-md-3 col-sm-3 " for="first-name ">Departement : <span class="required ">*</span>
                                    </label>
                                    <select class="form control " required id="libelle_dep" name="departement">
                                        <option >-----------</option> 
                                        {% for departement in departements %}
                                    <option value={{departement}}> {{departement}}</option>                         
                                    {% endfor %}

                                    </select>
                                    <!-- <select id="id_departement" class=" control-label col-md-4 col-sm-4 row ">
                                        {% for category in categories  %}
                                          <option value="{{ departement }} ">{{ departement.departement }}</option>
                                        {% endfor %}
                                      </select> -->
                                    <span class="tooltip ">Un nom ne peut pas faire moins de 2 caractères</span>
                                    <button class="btn btn-lg " style="background-color:red; color:green " onclick=window.location href="{% url 'service:departement' %}">
                                        <i class="fa fa-plus "></i> 
                                     </button>
                                </div>

                                <div class="ln_solid "></div>
                                <div class="item form-group ">
                                    <div class="col-md-6 col-sm-6 offset-md-3 ">
                                        <button class="btn btn-primary " type="button ">Cancel</button>


                                        <button id="send " type="submit " name="send " class="btn btn-primary waves-effect waves-light m-r-10">Submit</button>
                                    </div>
                                </div>

                            </form>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>

{% endblock content %}

templates/service/Bureau_detail.html
{% extends "base1.html" %}{% load staticfiles %} {% block title %}
<title>Liste des Bureau</title>{% endblock title %}{% block content %}
<div class="container">
    <br />
    <br />
    <div class="clearfix"></div>

    <div class="col-md-12 col-sm-12  ">
        <div class="x_panel">
            <div class="x_title">
                <h2>liste de Bureau</h2>
                <div class="add-product">
                    <a href="{% url 'service:bureau' %}">Ajouter Bureau</a>
                </div>
                <ul class="nav navbar-right panel_toolbox">
                    <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                    </li>


                </ul>
                <div class="clearfix"></div>

            </div>

            <div class="x_content">



                <div class="table-responsive">
                    <table class="table table-striped jambo_table bulk_action">
                        <thead>
                            <tr class="headings">
                                <th>
                                    <input type="checkbox" id="check-all" class="flat">
                                </th>
                                <th class="column-title">Id </th>
                                <th class="column-title">Numero Bureau</th>
                                <th class="column-title">Departement</th>
                                <th class="column-title no-link last"><span class="nobr">Action</span>
                                </th>
                                <th class="bulk-actions" colspan="7">
                                    <a class="antoo" style="color:#fff; font-weight:500;">Bulk Actions ( <span class="action-cnt"> </span> ) <i class="fa fa-chevron-down"></i></a>
                                </th>
                            </tr>
                        </thead>
                        {% for bureaux in bureau %}

                        <tbody>
                            <tr class="odd pointer">
                                <td class="a-center ">
                                    <input type="checkbox" class="flat" name="table_records">
                                </td>
                                <td class=" "></td>
                                <td class=" ">{{bureaux.num_bureau}}</td>
                                <td class="departement ">{{bureaux.departement}} </td>
                                <td class=" last">

                                    <ul>
                                        <a href="{% url 'service:oneburo' bureaux.id %}">Update|</a>

                                        <a href="{% url 'service:oneburodel' bureaux.id %}">Delete</a>
                                    </ul>
                                </td>
                            </tr>
                        </tbody>
                        {% endfor %}
                    </table>
                </div>


            </div>
        </div>
    </div>

    <div class="col-md-3 col-sm-3  offset-md-5">
        <button type="button" class="btn btn-primary">Cancel</button>

        <button type="submit" class="btn btn-success">Submit</button>
    </div>

</div>
{% endblock content %}

templates/service/Departement.html
{% extends "base1.html" %}{% load staticfiles %} {% block title %}
<title>Departement</title>{% endblock title %}{% block content %}
<div class="container">


    <div class="right_col" role="main">
        <div class="">

            <div class="clearfix"></div>
            <div class="row">
                <div class="col-md-12 col-sm-12 ">
                    <div class="x_panel">

                        <div class="x_content">
                            <br />
                            <form id="demo-form2" data-parsley-validate class="form-horizontal form-label-left" method="POST" action="{%url 'service:add_departement'%}">
                                {%csrf_token%}
                                <div class="page-header">
                                    <h3>Enregistrement des Departement</h3>
                                </div>
                                <div class=" form-group row">
                                    <label class="col-form-label col-md-3 col-sm-3 label-align" for="last-name">LIBELLE <span class="required">*</span>
                                      </label>
                                    <div class="col-md-4 col-sm-4 ">
                                        <input class="form-control" id="libelle_dep" name="libelle_dep" rows="1">
                                    </div>
                                </div>
                        </div>
                        <div class=" form-group row">
                            <label class="col-form-label col-md-3 col-sm-3 label-align" for="last-name">Description Departement <span class="required">*</span>
                              </label>
                            <div class="col-md-4 col-sm-4 ">
                                <textarea class="form-control" id="description" name="description" value="{{departement.description}}" rows="1"></textarea>
                            </div>
                        </div>

                        <div class="ln_solid"></div>
                        <div class="item form-group">
                            <div class="col-md-6 col-sm-6 offset-md-3">
                                <button class="btn btn-primary" type="button">Cancel</button>

                                <button id="send" type="submit" name="send" class="btn btn-success">Submit</button>
                            </div>
                        </div>

                        </form>
                    </div>
                </div>
            </div>
        </div>
        <div class="clearfix"></div>
    </div>
</div>
</div>
</div>
{% endblock content %}

templates/service/Departement_detail.html
{% extends "base1.html" %}{% load staticfiles %} {% block title %}
<title>Liste des Departement</title>{% endblock title %}{% block content %}
<div class="container">
    <br />
    <br />
    <!-- <div class="clearfix"></div> -->

    <div class="col-md-12 col-sm-12  ">
        <div class="x_panel">
            <div class="x_title">
                <h2>liste des Departement</h2>
                <div class="add-product">
                    <a href="{% url 'service:departement' %}">Ajouter Departement</a>
                </div>
                <ul class="nav navbar-right panel_toolbox">
                    <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                    </li>


                </ul>
                <div class="clearfix"></div>
            </div>

            <div class="x_content">



                <div class="table-responsive">
                    <table class="table table-striped jambo_table bulk_action">
                        <thead>
                            <tr class="headings">
                                <th>
                                    <input type="checkbox" id="check-all" class="flat">
                                </th>
                                <th class="column-title">Libelle Departement </th>
                                <th class="column-title">Description Departement </th>
                                <th class="column-title no-link last"><span class="nobr">Action</span>
                                </th>
                                <th class="bulk-actions" colspan="7">
                                    <a class="antoo" style="color:#fff; font-weight:500;">Bulk Actions ( <span class="action-cnt"> </span> ) <i class="fa fa-chevron-down"></i></a>
                                </th>
                            </tr>
                        </thead>
                        {% for departements in departement %}

                        <tbody>
                            <tr class="odd pointer">
                                <td class="a-center ">
                                    <input type="checkbox" class="flat" name="table_records">
                                </td>
                                <td class=" ">{{departements.libelle_dep}}</td>
                                <td class=" ">{{departements.description}}</td>
                                <td class=" last">
                                    <ul>
                                        <a href="{% url 'service:onedep' departements.id %}">Update|</a>
                                        <a href="{% url 'service:onedepdelete' departements.id %}">Delete</a>
                                    </ul>

                                </td>
                            </tr>


                        </tbody>
                        {% endfor %}
                    </table>
                </div>


            </div>
        </div>
    </div>
</div>
{% endblock content %}

templates/service/Intervenant_detail.html
{% extends "base1.html" %}{% load staticfiles %} {% block title %}
<title>Liste des Bureau</title>{% endblock title %}{% block content %}
<div class="container">
    <br />
    <br />

    <div class="clearfix"></div>
    <div class="col-md-12 col-sm-12  ">
        <div class="x_panel">
            <div class="x_title">
                <h2>liste des Intervenants</h2>
                <div class="add-product">
                    <a href="{% url 'service:intervenant' %}">Ajouter Intervenant</a>
                </div>
                <ul class="nav navbar-right panel_toolbox">
                    <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                    </li>


                </ul>
                <div class="clearfix"></div>
            </div>

            <div class="x_content">



                <div class="table-responsive">
                    <table class="table table-striped jambo_table bulk_action">
                        <thead>
                            <tr class="headings">
                                <th>
                                    <input type="checkbox" id="check-all" class="flat">
                                </th>
                                <th class="column-title">#</th>
                                <th class="column-title">Nom de l'Intervenants </th>
                                <th class="column-title">Telephone</th>
                                <th class="column-title">Couriel</th>
                                <th class="column-title no-link last"><span class="nobr">Action</span>
                                </th>
                                <th class="bulk-actions" colspan="7">
                                    <a class="antoo" style="color:#fff; font-weight:500;">Bulk Actions ( <span class="action-cnt"> </span> ) <i class="fa fa-chevron-down"></i></a>
                                </th>
                            </tr>
                        </thead>
                        {% for intervenants in intervenant %}



                        <tbody>
                            <tr class="odd pointer">
                                <td class="a-center ">
                                    <input type="checkbox" class="flat" name="table_records">
                                </td>
                                <td class=" "></td>
                                <td class=" ">{{intervenants.nom_intervenant}}</td>
                                <td class=" ">{{intervenants.telephone }}</td>
                                <td class=" ">{{intervenants.email}}</td>
                                <td class=" last">
                                    <ul>
                                        <a href="{% url 'service:oneinterv' intervenants.id %}">Update|</a>
                                        <a href="{% url 'service:oneintervdelete' intervenants.id %}">Delete</a>
                                    </ul>
                                </td>
                            </tr>

                        </tbody>
                        {% endfor %}
                    </table>
                </div>


            </div>
        </div>
    </div>
</div>
{% endblock content %}

templates/service/page.html
<h1>Book Edit</h1>
<form method="post">{% csrf_token %} {{ form.as_p }}
    <input type="submit" value="Submit" />
</form>