ParcInfo/urls.py
from django.urls import include, path
from django.contrib import admin


from django.conf.urls.static import static
from django.conf import settings




urlpatterns = [
    path('parc/', include('parc.urls')),
    path('blog/', include('blog.urls')),
    
    path('userprofile/', include('userprofile.urls')),
    path('intervention/', include('intervention.urls')),
    path('service/', include('service.urls')),

    path('admin/', admin.site.urls),
]

blog/urls.py
from django.urls import path


from . import views as blog

app_name="blog"
urlpatterns = [
    path('index', blog.index, name='index'),
    path('contact', blog.contact, name='contact'),
    path('accueil', blog.accueil, name='accueil'),
    path('accueill', blog.accueill, name='accueill'),
    path('forum', blog.forum, name='forum'),
    path('signup', blog.signup, name='signup'),
    path('signin', blog.signin, name='signin'),
    path('register', blog.register, name='register'),
    path('dashboard', blog.dashboard, name='dashboard'),
    path('login', blog.login, name='login'),
    path('logout', blog.logout, name='logout'),
    path('lock', blog.lock, name='lock'),
    path('inscription', blog.inscription, name='inscription'),
    path('email_detail', blog.email_detail, name='email_detail'),
    #path('contactview', blog.contactview, name='contactview'),
    
    path('listservice', blog.listservice, name='listservice'),
    path('listparc', blog.listparc, name='listparc'),
    path('listintervention', blog.listintervention, name='listintervention'),
    
    path('add_email', blog.add_email, name='add_email'),
    path('generalchat', blog.generalchat, name='generalchat'),
    path('post', blog.post, name='post'),
    path('uploads', blog.uploads, name='uploads'),
  
  
    #path('successview/', blog.successview, name='successview'),
    
    ]

parc/urls.py
from django.urls import path

from . import views as parc 

app_name="parc"
urlpatterns = [
         path('add_materiel', parc.add_materiel, name='add_materiel'),
         path('materiel', parc.materiel, name='materiel'),
         path('materiel_detail', parc.materiel_detail, name='materiel_detail'),
         path('onemateriel/<int:id>', parc.onemateriel, name='onemateriel'), 
         path('updatemate/<int:id>', parc.updatemate, name='updatemate'),
         path('onematerieldel/<int:id>', parc.onematerieldel, name='onematerieldel'), 
         path('deletemate/<int:id>', parc.deletemate, name='deletemate'),
         
         
         
         path('add_types_materiel', parc.add_types_materiel, name='add_types_materiel'),
         path('types_materiel', parc.types_materiel, name='types_materiel'),
         path('types_materiel_detail', parc.types_materiel_detail, name='types_materiel_detail'),
         path('onetypemater/<int:id>', parc.onetypemater, name='onetypemater'), 
         path('updatetypemate/<int:id>', parc.updatetypemate, name='updatetypemate'),
         path('onetypematerdel/<int:id>', parc.onetypematerdel, name='onetypematerdel'), 
         path('deletetypemate/<int:id>', parc.deletetypemate, name='deletetypemate'),
        
]

parc/models.py
from django.db import models
from django.utils.translation import gettext as _
from service.models import  Bureau
# Create your models here.

        
class Type_materiel(models.Model):
    libelle_materiel= models.CharField("libelle type_materiel", max_length=100, blank=True, null=True)
    description= models.CharField("Description", max_length=100, blank=True, null=True)
   

    class Meta:
        verbose_name = _("Type_materiel")
        verbose_name_plural = _("Types_materiels")

    def __str__(self):
        return '%s' % self.libelle_materiel

    def get_absolute_url(self):
        return reverse("type_materiel_detail", kwargs={"pk": self.pk})
            



class Materiel(models.Model):
    name = models.CharField("nom materiel",max_length=100, blank=True, null=True)
    numero_serie = models.CharField(_("numero_serie Materiel"), max_length=100, blank=True, null=True)
    caracteristique =  models.TextField("caracteristique", max_length=100, blank=True, null=True )
    bureau = models.ForeignKey(Bureau, related_name='bureau', on_delete=models.CASCADE, blank=True, null=True)
    type_materiel = models.ForeignKey(Type_materiel, related_name='type_materiel', on_delete=models.CASCADE, blank=True, null=True)
    
    class Meta:
        verbose_name = _("Materiel")
        verbose_name_plural = _("Materiels")
        
    def __str__(self):
        return '%s' % self.name

    def get_absolute_url(self):
        return reverse("materiel_detail",kwargs={"pk": self.pk})
    



# LIBELLE_MATERIEL= (
#     ('ORDINATEUR', 'ORDINATEUR'),
#     ('IMPRIMANT', 'IMPRIMANT'),
#     ('SCANNER', 'SCANNER'),
#     ('PHOTOCOPIEUSE', 'PHOTOCOPIEUSE'),
#     ('PERIPHERIQUE', 'PERIPHERIQUE'),
#     ('MONITEUR', 'MONITEUR'),
# ) 





        

parc/forms.py
from django.forms import ModelForm, Textarea
from django import forms
from parc.models import  Materiel, Type_materiel
    

# class MaterielForm(ModelForm):
#     class Meta:
#         model = Materiel
#         fields = ('name', 'numero_serie', 'caracteristique', 'bureau', 'type_materiel ')
        
 

# class Type_materielForm(ModelForm):
#     class Meta:
#         model = Type_materiel
#         fields = ('libelle_materiel', 'description')
       
       

parc/views.py
from django.shortcuts import render
from django.shortcuts import render, get_object_or_404, redirect
from .models import Materiel, Type_materiel
from service.models import  Bureau
from django.http import HttpResponse, HttpResponseRedirect,JsonResponse

# Create your views here.
def materiel (request):
    bureaux = Bureau.objects.all()
    type_materiels  = Type_materiel.objects.all()
    
    return render(request, 'parc/index.html', {'bureaux':bureaux, 'type_materiels':type_materiels})
          #============================View detail de materiel=======================

def materiel_detail (request):
    bureaux = Bureau.objects.all()
    type_materiels  = Type_materiel.objects.all()
    materiel = Materiel.objects.all()
    print("materiel")
    
    return render(request, 'parc/Materiel_detail.html', {'materiel':materiel})

           #============================ View save de materiel =======================
           
def add_materiel(request):
    materiel= Materiel.objects.all()
    bureau = Bureau.objects.get(num_bureau=request.POST.get("bureau"))
    types_materiel = Type_materiel.objects.get(libelle_materiel=request.POST.get("type_materiel"))
    if request.method == 'POST':
        materiel= Materiel(
            name = request.POST.get("name"),
            numero_serie = request.POST.get("numero_serie"),
            caracteristique = request.POST.get("caracteristique"),
            bureau = bureau,
            type_materiel = types_materiel,
                      
        )
        materiel.save()
       # mssage =  "% Bureau added succesfully"
        return HttpResponseRedirect('materiel_detail')
    else:
        mssage ="Echec"
    return render(request,'parc/Materiel.html',{'materiel':materiel})

        #============================ View Update et Delete de materiel ========================
        
def onemateriel(request, id):
    materiel = Materiel.objects.get(pk=id)
    bureaux = Bureau.objects.all()
    type_materiels = Type_materiel.objects.all()
    
    return render(request, 'parc/UpdateMate.html', { 'materiel':materiel, 'bureaux':bureaux, 'type_materiels':type_materiels})


def updatemate(request, id):
    materiel = Materiel.objects.get(pk=id)
    bureau = Bureau.objects.get(num_bureau=request.POST.get("bureau"))
    types_materiel = Type_materiel.objects.get(libelle_materiel=request.POST.get("type_materiel"))
    if request.method == 'POST':
        materiel= Materiel(
            id = id,
            name = request.POST.get("name"),
            numero_serie = request.POST.get("numero_serie"),
            caracteristique = request.POST.get("caracteristique"),
            bureau = bureau,
            type_materiel = types_materiel,
                      
        )
        materiel.save()
       # mssage =  "% Bureau added succesfully"
        return HttpResponseRedirect('/parc/materiel_detail')
    
def onematerieldel(request, id):
    materiel = Materiel.objects.get(pk=id)
    bureaux = Bureau.objects.all()
    type_materiels = Type_materiel.objects.all()
    
    return render(request, 'parc/DeleteMate.html', { 'materiel':materiel, 'bureaux':bureaux, 'type_materiels':type_materiels})


def deletemate(request, id):
    materiel = Materiel.objects.get(pk=id)
    materiel.delete()
    return HttpResponseRedirect('/parc/materiel_detail')
    






#=========================================Views de type de materiel===================================

def types_materiel (request):
    
    return render(request, 'parc/Types_materiel.html')

     #============================ View detail de types materiel ====================================

def types_materiel_detail (request):
    types_materiel  = Type_materiel.objects.all()
    
    return render(request, 'parc/Type_materiel_detail.html', {'types_materiel':types_materiel})

       #=============================== Views add de type materiel=============================

def add_types_materiel(request):
    types_materiel = Type_materiel.objects.all()
    if request.method == 'POST':
        types_materiel = Type_materiel(
            libelle_materiel = request.POST.get("libelle_materiel"),
            description = request.POST.get("description"),
                      
        )
        types_materiel.save()
       # mssage =  "% Bureau added succesfully"
        return HttpResponseRedirect('types_materiel_detail')
    else:
        mssage ="Echec"
    return render(request,'service/Types_materiel.html',{'types_materiel':types_materiel})

        #============================== Views Update et Delete de type materiel=================

def onetypemater(request, id):
    types_materiel = Type_materiel.objects.get(pk=id)
    
    return render(request, 'parc/UpdateTypeMate.html', {'types_materiel':types_materiel})

def updatetypemate(request, id):
    types_materiel = Type_materiel.objects.get(pk=id)
    if request.method == 'POST':
        types_materiel = Type_materiel(
            id = id, 
            libelle_materiel = request.POST.get("libelle_materiel"),
            description = request.POST.get("description"),
                      
        )
        types_materiel.save()
       # mssage =  "% Bureau added succesfully"
        return HttpResponseRedirect('/parc/types_materiel_detail')


def onetypematerdel(request, id):
    types_materiel = Type_materiel.objects.get(pk=id)
    
    return render(request, 'parc/DeleteTypeMate.html', {'types_materiel':types_materiel})


def deletetypemate(request, id):
    types_materiel = Type_materiel.objects.get(pk=id)
    types_materiel.delete()
    return HttpResponseRedirect('/parc/types_materiel_detail')
    

    


#========================================== END =======================================================

templates/parc/DeleteMate.html
{% extends "base1.html" %}{% load staticfiles %} {% block title %}
<title>Materiel</title>{% endblock title %}{% block content %}
<div class="container">


    <div class="right_col" role="main">
        <div class="">

            <div class="right_col" role="main">
                <div class="">
                    <div class="page-title">
                        <div class="title_left">
                            <h3>Enregistrement des Materiel</h3>
                            <h3> </h3>
                        </div>
                    </div>
                    <div class="clearfix"></div>

                    <div class="row">
                        <div class="col-md-12 col-sm-12">
                            <div class="x_panel">

                                <div class="x_content">

                                    <form class="form-horizontal form-label-left" method="POST" action="{%url 'parc:deletemate' materiel.id %}">
                                        {%csrf_token%}

                                        <div class="form-group row">
                                            <label class="control-label col-md-3 col-sm-3" for="first-name">Nom Materiel: <span class="required">*</span>
                                            </label>
                                            <div class="col-md-4 col-sm-4 ">
                                                <input type="text" id="name" required="required" name="name" value="{{materiel.name}}" class="form-control col-md-7 col-xs-12" onKeyPress="return verifieChar(event,0);">
                                            </div>
                                            <span class="tooltip">Un nom ne peut pas faire moins de 2 caractères</span>
                                        </div>

                                        <div class="form-group row">
                                            <label class="control-label col-md-3 col-sm-3" for="first-name">Numero Serie_Materiel: <span class="required">*</span>
                                            </label>
                                            <div class="col-md-4 col-sm-4 ">
                                                <input type="text" id="numero_serie" required="required" name="numero_serie" value="{{materiel.numero_serie}}" class="form-control col-md-7 col-xs-12" onKeyPress="return verifieChar(event,0);">
                                            </div>
                                            <span class="tooltip">Un nom ne peut pas faire moins de 2 caractères</span>
                                        </div>
                                        <div class="form-group row">
                                            <label class="control-label col-md-3 col-sm-3" for="first-name">Caracteristique: <span class="required">*</span>
                                            </label>
                                            <div class="col-md-4 col-sm-4 ">
                                                <input type="text" id="caracteristique" required="required" name="caracteristique" value="{{materiel.caracteristique}}" class="form-control col-md-7 col-xs-12">
                                            </div>
                                            <span class="tooltip">Un nom ne peut pas faire moins de 2 caractères</span>
                                        </div>



                                        <div class="form-group row">
                                            <label class="control-label col-md-3 col-sm-3" for="first-name">Bureau : <span class="required">*</span>
                                            </label>
                                            <select type="number" class="form control " required id="num_bureau" name="bureau" value={{materiel.bureau}}>
                                                {% for bureau in bureaux %}
                                            <option >{{bureau}}</option>                         
                                            {% endfor %}
                                            </select>
                                            <button class="btn btn-lg" style="background-color:red; color:green" onclick=window.location.href='http://127.0.0.1:8000/service/bureau' ; value=departement>
                                                <i class="fa fa-plus"></i> 
                                             </button>
                                        </div>
                                        <div class="form-group row">
                                            <label class="control-label col-md-3 col-sm-3" for="first-name">Type_materiel : <span class="required">*</span>
                                            </label>
                                            <select class="form control " required id="libelle_materiel" name="type_materiel" value={{materiel.type_materiel}}>
                                                {% for type_materiel in type_materiels %}
                                            <option >{{type_materiel}}</option>                         
                                            {% endfor %}
                                            </select>
                                            <button class="btn btn-lg" style="background-color:red; color:green" onclick=window.location.href='http://127.0.0.1:8000/service/bureau' ; value=departement>
                                                <i class="fa fa-plus"></i> 
                                             </button>
                                        </div>

                                        <!-- <div class="form-group row">
                                            <label class="control-label col-md-3 col-sm-3" for="first-name">Type_materiel : <span class="required">*</span>
                                            </label>
                                            <select class="form control " required id="libelle_materiel" name="type_materiel" value={{materiel.type_materiel}}>
                                                {% for type_materiel in type_materiels %}
                                            <option >{{type_materiel}}</option>                         
                                            {% endfor %}
                                            </select>
                                            <button class="btn btn-lg" style="background-color:red; color:green" onclick=window.location.href='http://127.0.0.1:8000/parc/caracteristique' ; value=departement>
                                                <i class="fa fa-plus"></i> 
                                             </button>
                                        </div> -->
                                        <div class="ln_solid"></div>
                                        <div class="form-group">
                                            <div class="col-md-9 col-sm-9  offset-md-3">
                                                <button type="button" class="btn btn-primary">Cancel</button>

                                                <button type="submit" class="btn btn-success">Delete</button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>


        </div>
    </div>
</div>
</div>
{% endblock content %}

templates/parc/DeleteTypeMate.html
{% extends "base1.html" %}{% load staticfiles %} {% block title %}
<title>Type_Materiel</title>{% endblock title %}{% block content %}
<div class="container">


    <div class="right_col" role="main">
        <div class="">
            <br>
            <br>

            <div class="right_col" role="main">
                <div class="">
                    <div class="page-title">
                        <div class="title_left">
                            <h3>Enregistrement des types de Materiel</h3>

                        </div>
                    </div>
                    <br>
                    <br>
                    <div class="clearfix"></div>

                    <div class="row">
                        <div class="col-md-12 col-sm-12">
                            <div class="x_panel">

                                <div class="x_content">

                                    <form class="form-horizontal form-label-left" novalidate method="POST" action="{%url 'parc:deletetypemate' types_materiel.id%}">
                                        {%csrf_token%}

                                        <div class="form-group row">
                                            <label class="control-label col-md-3 col-sm-3 ">Libelle Type_materiel :</label>
                                            <div class="col-md-4 col-sm-4 ">
                                                <input type="text" id="libelle_materiel" required="required" name="libelle_materiel" value="{{types_materiel.libelle_materiel}}" class="form-control col-md-7 col-xs-12" onKeyPress="return verifieChar(event,0);">
                                            </div>
                                            <span class="tooltip">Un nom ne peut pas faire moins de 2 caractères</span>
                                        </div>
                                        <div class="form-group row">
                                            <label class="control-label col-md-3 col-sm-3" for="first-name">Description: <span class="required">*</span>
                                            </label>
                                            <div class="col-md-4 col-sm-4 ">
                                                <input type="text" id="description" required="required" name="description" value="{{types_materiel.description}}" class="form-control col-md-7 col-xs-12" onKeyPress="return verifieChar(event,0);">
                                            </div>
                                            <span class="tooltip">Un nom ne peut pas faire moins de 2 caractères</span>
                                        </div>
                                        <div class="ln_solid"></div>
                                        <div class="form-group">
                                            <div class="col-md-9 col-sm-9  offset-md-3">
                                                <button type="button" class="btn btn-primary">Cancel</button>

                                                <button type="submit" class="btn btn-success">Delete</button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>


        </div>
    </div>
</div>
</div>
{% endblock content %}

templates/parc/Materiel_detail.html
{% extends "base1.html" %}{% load staticfiles %} {% block title %}
<title>Materiel_detail</title>{% endblock title %}{% block content %}
<div class="container">
    <br />
    <br />

    <div class="col-md-12 col-sm-12  ">
        <div class="x_panel">
            <div class="x_title">
                <h2>liste des Materiels</h2>
                <div class="add-product">
                    <a href="{% url 'parc:materiel' %}">Ajouter Materiel</a>
                </div>
                <ul class="nav navbar-right panel_toolbox">
                    <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                    </li>
                </ul>
                <div class="clearfix"></div>
            </div>
            <h2> </h2>
            <div class="x_content">
                <div class="table-responsive">
                    <table class="table table-striped jambo_table bulk_action">
                        <thead>
                            <tr class="headings">
                                <th>
                                    <input type="checkbox" id="check-all" class="flat">
                                </th>
                                <th class="column-title">#</th>
                                <th class="column-title">Nom Materiel </th>
                                <th class="column-title">Numero Serie_Materiel</th>
                                <th class="column-title">Caracteristique</th>
                                <th class="column-title">Bureau</th>
                                <th class="column-title">Types du materiel</th>
                                <th class="column-title no-link last"><span class="nobr">Action</span>
                                </th>
                                <th class="bulk-actions" colspan="7">
                                    <a class="antoo" style="color:#fff; font-weight:500;">Bulk Actions ( <span class="action-cnt"> </span> ) <i class="fa fa-chevron-down"></i></a>
                                </th>
                            </tr>
                        </thead>
                        {% for materiels in materiel %}

                        <tbody>
                            <tr class="odd pointer">
                                <td class="a-center ">
                                    <input type="checkbox" class="flat" name="table_records">
                                </td>
                                <td class=" "></td>
                                <td class=" ">{{materiels.name}}</td>
                                <td class=" ">{{materiels.numero_serie}}</td>
                                <td class=" ">{{materiels.caracteristique}}</td>
                                <td class=" ">{{materiels.bureau}}</td>
                                <td class=" ">{{materiels.type_materiel}}</td>
                                <td class=" last">

                                    <ul>
                                        <a href="{% url 'parc:onemateriel' materiels.id %}">Update|</a>
                                        <a href="{% url 'parc:onematerieldel' materiels.id %}">Delete</a>
                                    </ul>
                                </td>
                            </tr>



                        </tbody>
                        {% endfor %}
                    </table>
                </div>


            </div>
        </div>
    </div>

</div>
{% endblock content %}

templates/parc/Type_materiel_detail.html
{% extends "base1.html" %}{% load staticfiles %} {% block title %}
<title>Liste_type_Materiel</title>{% endblock title %}{% block content %}
<div class="container">
    <br />
    <br />


    <div class="right_col" role="main">
        <div class="">

            <div class="col-md-12 col-sm-12  ">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>liste des types de Materiel</h2>
                        <div class="add-product">
                            <a href="{% url 'parc:types_materiel' %}">Ajouter Type_materiel</a>
                        </div>
                        <ul class="nav navbar-right panel_toolbox">
                            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                            </li>
                        </ul>
                        <div class="clearfix"></div>
                    </div>
                    <h2> </h2>
                    <div class="x_content">
                        <div class="table-responsive">
                            <table class="table table-striped jambo_table bulk_action">
                                <thead>
                                    <tr class="headings">
                                        <th>
                                            <input type="checkbox" id="check-all" class="flat">
                                        </th>
                                        <th class="column-title">#</th>
                                        <th class="column-title">Libelle Type_materiel </th>
                                        <th class="column-title">Description</th>
                                        <th class="column-title no-link last"><span class="nobr">Action</span>
                                        </th>
                                        <th class="bulk-actions" colspan="7">
                                            <a class="antoo" style="color:#fff; font-weight:500;">Bulk Actions ( <span class="action-cnt"> </span> ) <i class="fa fa-chevron-down"></i></a>
                                        </th>
                                    </tr>
                                </thead>
                                {% for types_materiels in types_materiel %}

                                <tbody>
                                    <tr class="odd pointer">
                                        <td class="a-center ">
                                            <input type="checkbox" class="flat" name="table_records">
                                        </td>
                                        <td class=" "></td>
                                        <td class=" ">{{types_materiels.libelle_materiel}}</td>
                                        <td class=" ">{{types_materiels.description}}</td>
                                        <td class=" last">
                                            <ul>
                                                <a href="{% url 'parc:onetypemater' types_materiels.id %}">Update|</a>
                                                <a href="{% url 'parc:onetypematerdel' types_materiels.id %}">Delete</a>
                                            </ul>
                                        </td>
                                    </tr>



                                </tbody>
                                {% endfor %}
                            </table>
                        </div>


                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</div>
{% endblock content %}