ParcInfo/urls.py
from django.urls import include, path
from django.contrib import admin


from django.conf.urls.static import static
from django.conf import settings




urlpatterns = [
    path('parc/', include('parc.urls')),
    path('blog/', include('blog.urls')),
    
    path('userprofile/', include('userprofile.urls')),
    path('intervention/', include('intervention.urls')),
    path('service/', include('service.urls')),

    path('admin/', admin.site.urls),
]

blog/urls.py
from django.urls import path


from . import views as blog

app_name="blog"
urlpatterns = [
    path('index', blog.index, name='index'),
    path('contact', blog.contact, name='contact'),
    path('accueil', blog.accueil, name='accueil'),
    path('accueill', blog.accueill, name='accueill'),
    path('forum', blog.forum, name='forum'),
    path('signup', blog.signup, name='signup'),
    path('signin', blog.signin, name='signin'),
    path('register', blog.register, name='register'),
    path('dashboard', blog.dashboard, name='dashboard'),
    path('login', blog.login, name='login'),
    path('logout', blog.logout, name='logout'),
    path('lock', blog.lock, name='lock'),
    path('inscription', blog.inscription, name='inscription'),
    path('email_detail', blog.email_detail, name='email_detail'),
    #path('contactview', blog.contactview, name='contactview'),
    
    path('listservice', blog.listservice, name='listservice'),
    path('listparc', blog.listparc, name='listparc'),
    path('listintervention', blog.listintervention, name='listintervention'),
    
    path('add_email', blog.add_email, name='add_email'),
    path('generalchat', blog.generalchat, name='generalchat'),
    path('post', blog.post, name='post'),
    path('uploads', blog.uploads, name='uploads'),
  
  
    #path('successview/', blog.successview, name='successview'),
    
    ]

intervention/urls.py
from django.urls import path

from . import views as intervention

app_name="intervention"
urlpatterns = [
         path('intervention', intervention.intervention, name='intervention'),
         path('add_intervention', intervention.add_intervention, name='add_intervention'),
         path('intervention_detail', intervention.intervention_detail, name='intervention_detail'),
         path('oneinterven/<int:id>', intervention.oneinterven, name='oneinterven'),
         path('updateinterven/<int:id>', intervention.updateinterven, name='updateinterven'),
         path('oneintervendel/<int:id>', intervention.oneintervendel, name='oneintervendel'),
         path('deleteinterven/<int:id>', intervention.deleteinterven, name='deleteinterven'),
         
         
         
         
         path('panne', intervention.panne, name='panne'),
         path('add_panne', intervention.add_panne, name='add_panne'),
         path('panne_detail', intervention.panne_detail, name='panne_detail'),
         path('onepanne/<int:id>', intervention.onepanne, name='onepanne'),
         path('updatepan/<int:id>', intervention.updatepan, name='updatepan'),
         path('onepannedel/<int:id>', intervention.onepannedel, name='onepannedel'),
         path('deletepan/<int:id>', intervention.deletepan, name='deletepan'),
         
         
         
         path('type_panne', intervention.type_panne, name='type_panne'),
         path('add_type_panne', intervention.add_type_panne, name='add_type_panne'),
         path('type_panne_detail', intervention.type_panne_detail, name='type_panne_detail'),
         path('onetypepan/<int:id>', intervention.onetypepan, name='onetypepan'),
         path('updatetypepan/<int:id>', intervention.updatetypepan, name='updatetypepan'),
         path('onetypepandel/<int:id>', intervention.onetypepandel, name='onetypepandel'),
         path('deletetypepan/<int:id>', intervention.deletetypepan, name='deletetypepan'),
        
        
]

intervention/forms.py
from django.forms import ModelForm, Textarea
from intervention.models import Type_panne, Panne, Intervention
from django.contrib.admin import widgets

class Type_panneForm(ModelForm):
    class Meta:
        model = Type_panne
        fields = ('description', 'libelle_pan')
        


class PanneForm(ModelForm):
    class Meta:
        model = Panne
        fields = ('description', 'niveau', 'type_panne', 'intervenant', 'materiel')
        
        
  
class InterventionForm(ModelForm):
    date_interv = forms.DateTimeField(widget=widgets.AdminDateTimeWidget)
    class Meta:
        model = Intervention
        fields = ('libelle_interv', 'date_interv', 'accomplie', 'type_interv', 'consigne', 'intervenant', 'panne')
       

service/forms.py
from django.forms import ModelForm, Textarea
from django import forms
from .models import Departement, Bureau, Intervenant


class DepartementForm(ModelForm):
    class Meta:
        model = Departement
        fields = ('libelle_dep', 'description')
    
    # def clean_libelle_dep(self):
    #       libelle_dep = self.cleaned_data['libelle_dep']
    #       if self.instance.id:
    #          if Departement.objects.filter(libelle_dep=libelle_dep).exclude(id=self.instance.id):
    #             raise forms.ValidationError(
    #                         'Menu with this title already exists.')
    #          else:
    #             if Departement.objects.filter(libelle_dep=libelle_dep):
    #                raise forms.ValidationError(
    #                         'Menu with this subject already exists.')
    #             return libelle_dep

    # def clean_description(self):
    #       description = self.cleaned_data['description']
    #       if len(description) > 80:
    #          raise forms.ValidationError(
    #                         'content should not exceed 80 characters')
    #       return description
       

        

class BureauForm(ModelForm):
    num_bureau = forms.IntegerField()
    departement = forms.ModelChoiceField(queryset=Departement.objects.all(), initial=0)
    class Meta:
        model = Bureau
        fields = ('num_bureau', 'departement')
        
        
        
        
    # def __init__(self, *args, **kwargs):
    #     super().__init__(*args, **kwargs)
    #     self.fields['departement'].queryset = Departement.objects.none()

    #     if 'departement' in self.data:
    #         try:
                
    #           departement_id = int(self.data.get('departement'))
    #           self.fields['departement'].queryset = Departement.objects.filter(departement_id=departement_id).order_by('name')
    #         except (ValueError, TypeError):
    #             pass  # invalid input from the client; ignore and fallback to empty City queryset
    #     elif self.instance.pk:
    #         self.fields['departement'].queryset = self.instance.departement.departement_set.order_by('name')
        
 

class IntervenantForm(ModelForm):
    class Meta:
        model = Intervenant
        fields = ('nom_intervenant', 'telephone', 'email')
       
            

intervention/views.py
from django.shortcuts import render
from django.shortcuts import render, get_object_or_404, redirect
from intervention.models import Panne, Type_panne, Intervention
from service.models import  Intervenant
from parc.models import Materiel
from django.http import HttpResponse, HttpResponseRedirect,JsonResponse
from datetime import datetime


# Create your views here.
def intervention (request):
    intervention= Intervention.objects.all()
    pannes = Panne.objects.all()
    intervenants = Intervenant.objects.all()
   
    return render(request, 'intervention/Intervention.html', {'pannes':pannes, 'intervenants':intervenants})


def intervention_detail (request):
    intervention= Intervention.objects.all()
    pannes = Panne.objects.all()
    intervenant = Intervention.objects.all()
   
    return render(request, 'intervention/Intervention_detail.html', {'intervention':intervention})

     #============================== View add de intervention ===================================

def add_intervention(request):
    intervention= Intervention.objects.all()
    panne = Panne.objects.get(libelle_pan=request.POST.get("panne"))
    intervenant = Intervenant.objects.get(nom_intervenant=request.POST.get("intervenant"))
    
    
    if request.method == 'POST':
        intervention = Intervention(
            libelle_interv = request.POST.get("libelle_interv"),
            date_interv = request.POST.get("date_interv"),
            accomplie = request.POST.get("accomplie"),
            type_interv = request.POST.get("type_interv"),
            consigne = request.POST.get("consigne"),  
            intervenant = intervenant,
            panne = panne,
            
                      
        )
        intervention.save()
       # mssage =  "% Bureau added succesfully"
        return HttpResponseRedirect('intervention_detail')
    else:
        mssage ="Echec"
    return render(request,'intervention/Intervention.html',{'intervention':intervention})

     
     #======================== View Update et Delete de intervention ===========================
     
def oneinterven(request, id):
    intervention = Intervention.objects.get(pk=id)
    pannes = Panne.objects.all()
    intervenants = Intervenant.objects.all()
   
    return render(request, 'intervention/Updateinterven.html', {'intervention':intervention, 'pannes':pannes, 'intervenants':intervenants})


def updateinterven(request, id):
    intervention = Intervention.objects.get(pk=id)
    panne = Panne.objects.get(libelle_pan=request.POST.get("panne"))
    intervenant = Intervenant.objects.get(nom_intervenant=request.POST.get("intervenant"))
    
    if request.method == 'POST':
        intervention = Intervention(
            id = id, 
            libelle_interv = request.POST.get("libelle_interv"),
            date_interv = request.POST.get("date_interv"),
            accomplie = request.POST.get("accomplie"),
            type_interv = request.POST.get("type_interv"),
            consigne = request.POST.get("consigne"),  
            intervenant = intervenant,
            panne = panne,
            
                      
        )
        intervention.save()
       # mssage =  "% Bureau added succesfully"
        return HttpResponseRedirect('/intervention/intervention_detail')
    

def oneintervendel(request, id):
    intervention = Intervention.objects.get(pk=id)
    pannes = Panne.objects.all()
    intervenants = Intervenant.objects.all()
   
    return render(request, 'intervention/Deleteinterven.html', {'intervention':intervention, 'pannes':pannes, 'intervenants':intervenants})


def deleteinterven(request, id):
    intervention = Intervention.objects.get(pk=id)
    intervention.delete()
    return HttpResponseRedirect('/intervention/intervention_detail')
    


    

#==============================================Views de Panne===========================================
def panne (request):
    type_pannes = Type_panne.objects.all()
    intervenants = Intervenant.objects.all()
    materiels = Materiel.objects.all()
    
    
    return render(request, 'intervention/Panne.html', {'type_pannes':type_pannes, 'intervenants':intervenants, 'materiels':materiels})

    #=================================== View detail de panne =================================

def panne_detail (request):
    panne= Panne.objects.all()
    type_pannes = Type_panne.objects.all()
    intervenants = Intervenant.objects.all()
    materiels = Materiel.objects.all()
    
    
    return render(request, 'intervention/Panne_detail.html', {'panne':panne})

      #=================================== View add de panne =================================
      
def add_panne(request):
    panne= Panne.objects.all()
    type_panne = Type_panne.objects.get(libelle_pan=request.POST.get("type_panne"))
    intervenant = Intervenant.objects.get(nom_intervenant=request.POST.get("intervenant"))
    materiel = Materiel.objects.get(name=request.POST.get("materiel") )
    if request.method == 'POST':
        panne = Panne(
            libelle_pan = request.POST.get("libelle_pan"),
            description = request.POST.get("description"),
            niveau = request.POST.get("niveau"),
            type_panne = type_panne,
            intervenant = intervenant,
            materiel = materiel,
                      
        )
        panne.save()
       # mssage =  "% Bureau added succesfully"
        return HttpResponseRedirect('panne_detail')
    else:
        mssage ="Echec"
    return render(request,'intervention/Panne.html',{'panne':panne})

    
      #================================ View Update et Delete de panne =======================
      
def onepanne(request, id):
    panne = Panne.objects.get(pk=id)
    type_pannes = Type_panne.objects.all()
    intervenants = Intervenant.objects.all()
    materiels = Materiel.objects.all()
    
    return render(request, 'intervention/UpdatePan.html', {'panne':panne, 'type_pannes':type_pannes, 'intervenants':intervenants, 'materiels':materiels})


def updatepan(request, id):
    panne = Panne.objects.get(pk=id)
    type_panne = Type_panne.objects.get(libelle_pan=request.POST.get("type_panne"))
    intervenant = Intervenant.objects.get(nom_intervenant=request.POST.get("intervenant"))
    materiel = Materiel.objects.get(name=request.POST.get("materiel") )
    if request.method == 'POST':
        panne = Panne(
            id = id,
            libelle_pan = request.POST.get("libelle_pan"),
            description = request.POST.get("description"),
            niveau = request.POST.get("niveau"),
            type_panne = type_panne,
            intervenant = intervenant,
            materiel = materiel,
                      
        )
        panne.save()
       # mssage =  "% Bureau added succesfully"
        return HttpResponseRedirect('/intervention/panne_detail')
    
    
def onepannedel(request, id):
    panne = Panne.objects.get(pk=id)
    type_pannes = Type_panne.objects.all()
    intervenants = Intervenant.objects.all()
    materiels = Materiel.objects.all()
    
    return render(request, 'intervention/DeletePan.html', {'panne':panne, 'type_pannes':type_pannes, 'intervenants':intervenants, 'materiels':materiels})


def deletepan(request, id):
    panne = Panne.objects.get(pk=id)
    panne.delete()
    return HttpResponseRedirect('/intervention/panne_detail')
    


    

#==============================================Views de type de panne================================
def type_panne (request):
    
    return render(request, 'intervention/Type_panne.html')

    #=================================== View detail de type panne =================================
def type_panne_detail (request):
    type_panne = Type_panne.objects.all()
    
    return render(request, 'intervention/Type_panne_detail.html',{'type_panne':type_panne})

    #=================================== View add de type panne ====================================

def add_type_panne(request):
    type_panne= Type_panne.objects.all()
    if request.method == 'POST':
        type_panne = Type_panne(
            libelle_pan = request.POST.get("libelle_pan"),
            description = request.POST.get("description"),
                      
        )
        type_panne.save()
        return HttpResponseRedirect('type_panne_detail')
    else:
        mssage ="Echec"
    return render(request,'intervention/Type_panne.html',{'type_panne':type_panne})

    #=================================== View Update et Delete de type panne ======================
    
def onetypepan(request, id):
    type_panne = Type_panne.objects.get(pk=id)
    
    return render(request, 'intervention/UpdateTypepan.html',{'type_panne':type_panne})


def updatetypepan(request, id):
    type_panne = Type_panne.objects.get(pk=id)
    if request.method == 'POST':
        type_panne = Type_panne(
            id = id,
            libelle_pan = request.POST.get("libelle_pan"),
            description = request.POST.get("description"),
                      
        )
        type_panne.save()
        return HttpResponseRedirect('/intervention/type_panne_detail')
    
    
def onetypepandel(request, id):
    type_panne = Type_panne.objects.get(pk=id)
    
    return render(request, 'intervention/DeleteTypepan.html',{'type_panne':type_panne})

def deletetypepan(request, id):
    type_panne = Type_panne.objects.get(pk=id)
    type_panne.delete()
    return HttpResponseRedirect('/intervention/type_panne_detail')
    

#==============================================Views end====================================================

templates/intervention/DeleteTypepan.html
{% extends "base1.html" %}{% load staticfiles %} {% block title %}
<title>Type de panne</title>{% endblock title %}{% block content %}
<div class="container">


    <div class="right_col" role="main">
        <div class="">

            <div class="right_col" role="main">
                <div class="">
                    <div class="page-title">
                        <div class="title_left">
                            <h3>Enregistrement des types de panne</h3>
                            <h3> </h3>
                        </div>
                    </div>
                    <div class="clearfix"></div>

                    <div class="row">
                        <div class="col-md-12 col-sm-12">
                            <div class="x_panel">

                                <div class="x_content">

                                    <form class="form-horizontal form-label-left" method="POST" action="{%url 'intervention:deletetypepan' type_panne.id %}">
                                        {%csrf_token%}
                                        <div class="form-group row">
                                            <label class="control-label col-md-3 col-sm-3" for="first-name">Libelle type_panne: <span class="required">*</span>
                                            </label>
                                            <div class="col-md-4 col-sm-4 ">
                                                <input type="text" id="libelle_pan" required="required" name="libelle_pan" value="{{type_panne.libelle_pan}}" class="form-control col-md-7 col-xs-12" onKeyPress="return verifieChar(event,0);">
                                            </div>
                                            <span class="tooltip">Un nom ne peut pas faire moins de 2 caractères</span>
                                        </div>
                                        <div class="form-group row">
                                            <label class="control-label col-md-3 col-sm-3" for="first-name">Description type_panne: <span class="required">*</span>
                                            </label>
                                            <div class="col-md-4 col-sm-4 ">
                                                <input type="text" id="description" required="required" name="description" value="{{type_panne.description}}" class="form-control col-md-7 col-xs-12" onKeyPress="return verifieChar(event,0);">
                                            </div>
                                            <span class="tooltip">Un nom ne peut pas faire moins de 2 caractères</span>
                                        </div>
                                        <div class="ln_solid"></div>
                                        <div class="form-group">
                                            <div class="col-md-9 col-sm-9  offset-md-3">
                                                <button type="button" class="btn btn-primary">Cancel</button>

                                                <button type="submit" class="btn btn-success">Delete</button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>


        </div>
    </div>
</div>
</div>
{% endblock content %}

templates/intervention/Intervention_detail.html
{% extends "base1.html" %}{% load staticfiles %} {% block title %}
<title> Liste des Interventions</title>{% endblock title %}{% block content %}
<div class="container">
    <br />
    <br />
    <div class="col-md-12 col-sm-12  ">
        <div class="x_panel">
            <div class="x_title">
                <h2>liste des Interventions</h2>
                <div class="add-product">
                    <a href="{% url 'intervention:intervention' %}">Ajouter Intervention</a>
                </div>
                <ul class="nav navbar-right panel_toolbox">
                    <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                    </li>
                </ul>
                <div class="clearfix"></div>
            </div>
            <h2> </h2>
            <div class="x_content">
                <br />
                <div class="table-responsive">
                    <table class="table table-striped jambo_table bulk_action">
                        <thead>
                            <tr class="headings">
                                <th>
                                    <input type="checkbox" id="check-all" class="flat">
                                </th>
                                <th class="column-title">#</th>
                                <th class="column-title">Libelle de l'intervention </th>
                                <th class="column-title">Date de l'intervention</th>
                                <th class="column-title">Statut</th>
                                <th class="column-title">Type d'intervention</th>
                                <th class="column-title">Consigne</th>
                                <th class="column-title">Intervenant</th>
                                <th class="column-title">Panne</th>


                                <th class="column-title no-link last"><span class="nobr">Action</span>
                                </th>
                                <th class="bulk-actions" colspan="7">
                                    <a class="antoo" style="color:#fff; font-weight:500;">Bulk Actions ( <span class="action-cnt"> </span> ) <i class="fa fa-chevron-down"></i></a>
                                </th>
                            </tr>
                        </thead>
                        {% for interventions in intervention %}

                        <tbody>
                            <tr class="odd pointer">
                                <td class="a-center ">
                                    <input type="checkbox" class="flat" name="table_records">
                                </td>
                                <td class=" "></td>
                                <td class=" ">{{interventions.libelle_interv}}</td>
                                <td class=" ">{{interventions.date_interv}}</td>
                                <td class=" ">{{interventions.accomplie}}</td>
                                <td class=" ">{{interventions.type_interv}}</td>
                                <td class=" ">{{interventions.consigne}}</td>
                                <td class=" ">{{interventions.intervenant}}</td>
                                <td class=" ">{{interventions.panne}}</td>
                                <td class=" btn btn-primary waves-effect waves-light m-r-10">

                                    <ul>
                                        <a href="{% url 'intervention:oneinterven' interventions.id %}">Update|</a>
                                        <a href="{% url 'intervention:oneintervendel' interventions.id %}">Delete</a>
                                    </ul>

                                </td>
                            </tr>

                        </tbody>
                        {% endfor %}
                    </table>
                </div>


            </div>
        </div>
    </div>

</div>
{% endblock content %}

templates/intervention/Panne_detail.html
{% extends "base1.html" %}{% load staticfiles %} {% block title %}
<title>Liste des Pannes</title>{% endblock title %}{% block content %}
<div class="container">
    <br />
    <br />
    <div class="col-md-12 col-sm-12  ">
        <div class="x_panel">
            <div class="x_title">
                <h2>liste des Pannes</h2>
                <div class="add-product">
                    <a href="{% url 'intervention:panne' %}">Ajouter Panne</a>
                </div>
                <ul class="nav navbar-right panel_toolbox">
                    <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                    </li>
                </ul>
                <div class="clearfix"></div>
            </div>
            <h2> </h2>
            <div class="x_content">
                <div class="table-responsive">
                    <table class="table table-striped jambo_table bulk_action">
                        <thead>
                            <tr class="headings">
                                <th>
                                    <input type="checkbox" id="check-all" class="flat">
                                </th>
                                <th class="column-title">#</th>
                                <th class="column-title">Libelle panne</th>
                                <th class="column-title">Description panne</th>
                                <th class="column-title">Degree panne</th>
                                <th class="column-title">Type Panne</th>
                                <th class="column-title">Intervenant</th>
                                <th class="column-title">Materiel</th>
                                <th class="column-title no-link last"><span class="nobr">Action</span>
                                </th>
                                <th class="bulk-actions" colspan="7">
                                    <a class="antoo" style="color:#fff; font-weight:500;">Bulk Actions ( <span class="action-cnt"> </span> ) <i class="fa fa-chevron-down"></i></a>
                                </th>
                            </tr>
                        </thead>
                        {% for pannes in panne %}

                        <tbody>
                            <tr class="odd pointer">
                                <td class="a-center ">
                                    <input type="checkbox" class="flat" name="table_records">
                                </td>
                                <td class=" "></td>
                                <td class=" ">{{pannes.libelle_pan}}</td>
                                <td class=" ">{{pannes.description}}</td>
                                <td class=" ">{{pannes.niveau}}</td>
                                <td class=" ">{{pannes.type_panne}}</td>
                                <td class=" ">{{pannes.intervenant}}</td>
                                <td class=" ">{{pannes.materiel}}</td>
                                <td class=" btn btn-primary waves-effect waves-light m-r-10" style="color:#fff" ;>

                                    <ul>
                                        <a href="{% url 'intervention:onepanne' pannes.id %}">Update|</a>
                                        <a href="{% url 'intervention:onepannedel' pannes.id %}">Delete</a>
                                    </ul>
                                </td>
                            </tr>
                        </tbody>
                        {% endfor %}
                    </table>
                </div>


            </div>
        </div>
    </div>

</div>
{% endblock content %}

templates/intervention/Type_panne_detail.html
{% extends "base1.html" %}{% load staticfiles %} {% block title %}
<title>Liste des Type de panne</title>{% endblock title %}{% block content %}
<div class="container">
    <br />
    <br />
    <div class="col-md-12 col-sm-12  ">
        <div class="x_panel">
            <div class="x_title">
                <h2>liste des types de panne</h2>
                <div class="add-product">
                    <a href="{% url 'intervention:type_panne' %}">Ajouter type_panne</a>
                </div>
                <ul class="nav navbar-right panel_toolbox">
                    <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                    </li>
                </ul>
                <div class="clearfix"></div>
            </div>
            <h2> </h2>
            <div class="x_content">
                <div class="table-responsive">
                    <table class="table table-striped jambo_table bulk_action">
                        <thead>
                            <tr class="headings">
                                <th>
                                    <input type="checkbox" id="check-all" class="flat">
                                </th>
                                <th class="column-title">#</th>
                                <th class="column-title">Libelle type_panne : </th>
                                <th class="column-title">Description type_panne :</th>
                                <th class="column-title no-link last"><span class="nobr">Action</span>
                                </th>

                            </tr>
                        </thead>
                        {% for type_pannes in type_panne %}

                        <tbody>
                            <tr class="odd pointer">
                                <td class="a-center ">
                                    <input type="checkbox" class="flat" name="table_records">
                                </td>
                                <td class=" "></td>
                                <td class=" ">{{type_pannes.libelle_pan}}</td>
                                <td class=" ">{{type_pannes.description}}</td>
                                <td class=" btn btn-primary waves-effect waves-light m-r-10">

                                    <ul>
                                        <a href="{% url 'intervention:onetypepan' type_pannes.id %}">Update|</a>
                                        <a href="{% url 'intervention:onetypepandel' type_pannes.id %}">Delete</a>
                                    </ul>
                                </td>
                            </tr>
                        </tbody>
                        {% endfor %}
                    </table>
                </div>


            </div>
        </div>
    </div>
</div>
{% endblock content %}