ParcInfo/urls.py
from django.urls import include, path
from django.contrib import admin


from django.conf.urls.static import static
from django.conf import settings




urlpatterns = [
    path('parc/', include('parc.urls')),
    path('blog/', include('blog.urls')),
    
    path('userprofile/', include('userprofile.urls')),
    path('intervention/', include('intervention.urls')),
    path('service/', include('service.urls')),

    path('admin/', admin.site.urls),
]

blog/urls.py
from django.urls import path


from . import views as blog

app_name="blog"
urlpatterns = [
    path('index', blog.index, name='index'),
    path('contact', blog.contact, name='contact'),
    path('accueil', blog.accueil, name='accueil'),
    path('accueill', blog.accueill, name='accueill'),
    path('forum', blog.forum, name='forum'),
    path('signup', blog.signup, name='signup'),
    path('signin', blog.signin, name='signin'),
    path('register', blog.register, name='register'),
    path('dashboard', blog.dashboard, name='dashboard'),
    path('login', blog.login, name='login'),
    path('logout', blog.logout, name='logout'),
    path('lock', blog.lock, name='lock'),
    path('inscription', blog.inscription, name='inscription'),
    path('email_detail', blog.email_detail, name='email_detail'),
    #path('contactview', blog.contactview, name='contactview'),
    
    path('listservice', blog.listservice, name='listservice'),
    path('listparc', blog.listparc, name='listparc'),
    path('listintervention', blog.listintervention, name='listintervention'),
    
    path('add_email', blog.add_email, name='add_email'),
    path('generalchat', blog.generalchat, name='generalchat'),
    path('post', blog.post, name='post'),
    path('uploads', blog.uploads, name='uploads'),
  
  
    #path('successview/', blog.successview, name='successview'),
    
    ]

intervention/urls.py
from django.urls import path

from . import views as intervention

app_name="intervention"
urlpatterns = [
         path('intervention', intervention.intervention, name='intervention'),
         path('add_intervention', intervention.add_intervention, name='add_intervention'),
         path('intervention_detail', intervention.intervention_detail, name='intervention_detail'),
         path('oneinterven/<int:id>', intervention.oneinterven, name='oneinterven'),
         path('updateinterven/<int:id>', intervention.updateinterven, name='updateinterven'),
         path('oneintervendel/<int:id>', intervention.oneintervendel, name='oneintervendel'),
         path('deleteinterven/<int:id>', intervention.deleteinterven, name='deleteinterven'),
         
         
         
         
         path('panne', intervention.panne, name='panne'),
         path('add_panne', intervention.add_panne, name='add_panne'),
         path('panne_detail', intervention.panne_detail, name='panne_detail'),
         path('onepanne/<int:id>', intervention.onepanne, name='onepanne'),
         path('updatepan/<int:id>', intervention.updatepan, name='updatepan'),
         path('onepannedel/<int:id>', intervention.onepannedel, name='onepannedel'),
         path('deletepan/<int:id>', intervention.deletepan, name='deletepan'),
         
         
         
         path('type_panne', intervention.type_panne, name='type_panne'),
         path('add_type_panne', intervention.add_type_panne, name='add_type_panne'),
         path('type_panne_detail', intervention.type_panne_detail, name='type_panne_detail'),
         path('onetypepan/<int:id>', intervention.onetypepan, name='onetypepan'),
         path('updatetypepan/<int:id>', intervention.updatetypepan, name='updatetypepan'),
         path('onetypepandel/<int:id>', intervention.onetypepandel, name='onetypepandel'),
         path('deletetypepan/<int:id>', intervention.deletetypepan, name='deletetypepan'),
        
        
]

parc/urls.py
from django.urls import path

from . import views as parc 

app_name="parc"
urlpatterns = [
         path('add_materiel', parc.add_materiel, name='add_materiel'),
         path('materiel', parc.materiel, name='materiel'),
         path('materiel_detail', parc.materiel_detail, name='materiel_detail'),
         path('onemateriel/<int:id>', parc.onemateriel, name='onemateriel'), 
         path('updatemate/<int:id>', parc.updatemate, name='updatemate'),
         path('onematerieldel/<int:id>', parc.onematerieldel, name='onematerieldel'), 
         path('deletemate/<int:id>', parc.deletemate, name='deletemate'),
         
         
         
         path('add_types_materiel', parc.add_types_materiel, name='add_types_materiel'),
         path('types_materiel', parc.types_materiel, name='types_materiel'),
         path('types_materiel_detail', parc.types_materiel_detail, name='types_materiel_detail'),
         path('onetypemater/<int:id>', parc.onetypemater, name='onetypemater'), 
         path('updatetypemate/<int:id>', parc.updatetypemate, name='updatetypemate'),
         path('onetypematerdel/<int:id>', parc.onetypematerdel, name='onetypematerdel'), 
         path('deletetypemate/<int:id>', parc.deletetypemate, name='deletetypemate'),
        
]

service/urls.py
from django.urls import path

from . import views as service

app_name="service"
urlpatterns = [
         
         path('bureau', service.bureau, name='bureau'), 
         path('bureau_detail', service.bureau_detail, name='bureau_detail'), 
         path('add_bureau', service.add_bureau, name='add_bureau'),   
         path('oneburo/<int:id>', service.oneburo, name='oneburo'), 
         path('updateburo/<int:id>', service.updateburo, name='updateburo'),
         path('oneburodel/<int:id>', service.oneburodel, name='oneburodel'), 
         path('deleteburo/<int:id>', service.deleteburo, name='deleteburo'), 
         
        
         
         path('departement', service.departement, name='departement'),
         path('departement_detail', service.departement_detail, name='departement_detail'),      
         path('add_departement', service.add_departement, name='add_departement'), 
         path('onedep/<int:id>', service.onedep, name='onedep'), 
         path('updatedep/<int:id>', service.updatedep, name='updatedep'), 
         path('onedepdelete/<int:id>', service.onedepdelete, name='onedepdelete'), 
         path('deletedep/<int:id>', service.deletedep, name='deletedep'), 
         
         
         path('oneinterv/<int:id>', service.oneinterv, name='oneinterv'), 
         path('updateinterv/<int:id>', service.updateinterv, name='updateinterv'),
         path('oneintervdelete/<int:id>', service.oneintervdelete, name='oneintervdelete'), 
         path('deleteinterv/<int:id>', service.deleteinterv, name='deleteinterv'), 
         path('add_intervenant', service.add_intervenant, name='add_intervenant'),   
         path('intervenant', service.intervenant, name='intervenant'),
         path('intervenant_detail', service.intervenant_detail, name='intervenant_detail'),
         path('page', service.page, name='page'), 
        
]

userprofile/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from django.http import *
from django.views.generic import TemplateView
from django.conf import settings


from . import views as userprofile

app_name="userprofile"
urlpatterns = [
    path('', userprofile.index, name='index'),
    
    #path('signup', userprofile.signup, name='signup'),
    
    path('loginView', userprofile.loginView, name='loginView'),
    path('logoutView', userprofile.logoutView, name='logoutView'),
    #path(r'^backoffice/$', TemplateView.as_view(template_name='backoffice/accueil.html'), name='accueil'),

    
    ]

blog/forms.py
from django.forms import ModelForm, Textarea
from django import forms
from .models import Email, Contact, Chat
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from blog.models import UserProfileInfo
 

class ContactForm(forms.Form):
    from_email = forms.EmailField(required=True)
    subject = forms.CharField(required=True)
    message = forms.CharField(widget=forms.Textarea, required=True)
    
    

class EmailForm(forms.Form):
    class Meta:
        model = Email
        fields = ('name', 'Subject', 'message')
        

class ChatForm(forms.Form):
    
    class Meta:
        model = Chat
        fields = ('created', 'user', 'message', 'file_upload')
        

 
class CustomUserCreationForm(forms.Form):
    username = forms.CharField(label='Enter Username', min_length=4, max_length=150)
    email = forms.EmailField(label='Enter email')
    password1 = forms.CharField(label='Enter password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Confirm password', widget=forms.PasswordInput)
 
    def clean_username(self):
        username = self.cleaned_data['username'].lower()
        r = User.objects.filter(username=username)
        if r.count():
            raise  ValidationError("Username already exists")
        return username
 
    def clean_email(self):
        email = self.cleaned_data['email'].lower()
        r = User.objects.filter(email=email)
        if r.count():
            raise  ValidationError("Email already exists")
        return email
 
    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')
 
        if password1 and password2 and password1 != password2:
            raise ValidationError("Password don't match")
 
        return password2
 
    def save(self, commit=True):
        user = User.objects.create_user(
            self.cleaned_data['username'],
            self.cleaned_data['email'],
            self.cleaned_data['password1']
        )
        return user
    
class SignUpForm(UserCreationForm):
    

    class Meta:
        model = User
        fields = ('username', 'password1', 'password2',)
        

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model = User
        fields = ('username','password','email')
        
class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site','profile_pic')

parc/forms.py
from django.forms import ModelForm, Textarea
from django import forms
from parc.models import  Materiel, Type_materiel
    

# class MaterielForm(ModelForm):
#     class Meta:
#         model = Materiel
#         fields = ('name', 'numero_serie', 'caracteristique', 'bureau', 'type_materiel ')
        
 

# class Type_materielForm(ModelForm):
#     class Meta:
#         model = Type_materiel
#         fields = ('libelle_materiel', 'description')
       
       

blog/views.py
from django.core.mail import BadHeaderError, EmailMessage
from django.shortcuts import render, get_object_or_404, redirect, render_to_response
from django.http import HttpResponse, HttpResponseRedirect,JsonResponse
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.urls import reverse
from datetime import datetime
from django.contrib.auth.models import User
from django.contrib.auth import login, authenticate, get_user_model
from django.contrib.auth.forms import UserCreationForm
from .forms import CustomUserCreationForm
from django.contrib.auth.forms import AuthenticationForm 
from django.contrib import auth
from collections import OrderedDict
from blog.fusioncharts import FusionCharts
from django.views import generic
from service.models import Bureau, Intervenant
from intervention.models import Intervention, Panne
from .models import Email
from .forms import EmailForm, ChatForm, SignUpForm, forms
from blog.forms import UserForm,UserProfileInfoForm



from .models import Article

def index (request):
    
   
    return render(request, 'blog/Index.html')

def accueill (request):
    
   
    return render(request, 'blog/Accueil1.html')


def accueil (request):
    return render(request, 'blog/Accueil.html')

def contact (request):
    return render(request, 'blog/Contact.html')


def contactview (request):
    return render(request, 'blog/ContactView.html')

def email_detail (request):
    email= Email.objects.all()
    return render(request, 'blog/Inbox.html',{'email':email})


def lock (request):
    return render(request, 'blog/Lock.html')

def inscription (request):
    return render(request, 'blog/Inscription.html')




def login (request):
    return render(request, 'blog/Login.html')


def logout (request):
    return render(request, 'blog/Accueil.html')

  #===================================== Chat views ================================
  
def generalchat(request):
        c = Chat.objects.all()
        documents = Document.objects.all() #file upload
        return render(request, "channels/Forum.html", {'generalchat': 'active', 'chat': c, 'documents': documents})

  
def post(request):
    if request.method == "POST":
        msg = request.POST.get('msgbox', None)
        time = datetime.now()
        c = Chat(user=request.user, message=msg, created=time)

        c = Chat(user=request.user, message=msg)

        if msg != '':            
           c.save()
        return JsonResponse({ 'msg': msg, 'user': c.user.username})
    else:
       return HttpResponse('Request must be POST.')
   


def uploads(request):
    if request.method == 'POST':
        form = DocumentForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('forum')
    else:
       form = DocumentForm()
       return render(request, 'channels/uploads.html', {
    'form': form
    })

  #============================= Login and register views =========================
 
def signup(request):
    # if request.user.is_authenticated:
    #     return redirect('blog:signin', username=request.user.username)
 
   
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = auth.authenticate(username=username, password=password)
 
        if user is not None:
            # correct username and password login the user
            auth.login(request, user)
            return redirect('/blog/accueill')
 
        else:
            messages.error(request, 'Error wrong username/password')
 
    return render(request, 'blog/Login.html')
 
 
def signin(request):
    auth.logout(request)
    return redirect('/blog/accueil')
   
 
 
def register(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            profile = profile_form.save(commit=False)
            profile.user = user
            if 'profile_pic' in request.FILES:
                print('found it')
                profile.profile_pic = request.FILES['profile_pic']
            profile.save()
            registered = True
            return redirect('/blog/login')
        else:
            print(user_form.errors,profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()
    return render(request,'blog/Inscription.html',
                          {'user_form':user_form,
                           'profile_form':profile_form,
                           'registered':registered})



def add_email (request):   
    email= Email.objects.all()
    if request.method == 'POST':
        email= Email(
            name = request.POST.get("name"),
            degree = request.POST.get("degree"),
            Subject = request.POST.get("Subject"),  
            message = request.POST.get("message"),           
        )
        email.save()
        return HttpResponseRedirect('email_detail')
    else:
        message ="Echec"
    return render(request,'blog/Contact.html',{'email':email})

# def oneemaildep(request, id):
#     email= Email.objects.get(pk=id)
#     return render(request, 'blog/Deletemail.html', {'email':email})

# def deletemail(request,id):
#     email= Email.objects.get(pk=id)
#     email.delete()
#     return HttpResponseRedirect('email_detail')
    



def forum (request):
    return render(request, 'blog/Forum.html')

def dashboard (request):
    intervention= Intervention.objects.all()
    chartObj = FusionCharts( 'pie3d', 'ex1', '1000', '400', 'chart-1', 'jsonurl', "/static/data/data.json")
   
    return render(request, 'blog/Tableau_de_Bord.html', {'intervention':intervention, 'output': chartObj.render()})


   #===========================================================================
   
   
def listservice (request):
    bureau = Bureau.objects.all()
    return render(request, 'blog/Services.html')

def listparc (request):
    return render(request, 'blog/Parcs.html')

def listintervention (request):
    return render(request, 'blog/Interventi.html')

    #============================== Chat views==================================
    

templates/blog/Forum.html
{% extends "base.html" %}{% load staticfiles %} {% block title %}
<title>Forum</title>{% endblock title %}{% block content %}
<div class="container">
    <h1>Y@@@@raaah</h1>

    <script src="{% static 'js/https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js' %}"></script>
    <script src="{% static 'js/http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js' %}"></script>

    <div id="chat-body" class="panel panel-default">
        <div id="panel-heading" class="panel-heading">
            <h4>General Chat</h4>
        </div>
        <div id="msg-list-div" class="panel-body">
            <ul id="msg-list" class="list-group">

                {% for obj in chat %} {%if obj.user == request.user %}
                <li class="text-right list-group-item">
                    <font color="#3498DB">{{ obj.user }}</font><br>
                    <font color="#000000"></font>{{ obj.message }}
                    <br>
                    <font size="1">{{ obj.created }}</font>
                </li>
                <br> {% else %}
                <li class="text-left list-group-item">
                    <font color="#1ABC9C">{{ obj.user }}</font><br>
                    <font color="#000000"></font>{{ obj.message }}
                    <br>
                    <font size="1">{{ obj.created }}</font>
                </li>
                </li>
                <br> {%endif%} {% empty %}
                <li class="text-right list-group-item">No messages yet.</li>
                {% endfor %}
                <h4>Files</h4>
                {% for obj in documents %} {%if obj.userUpload == request.user %}
                <li class="text-right list-group-item">
                    <font color="#3498DB">{{ obj.userUpload }}</font><br>
                    <a href="{{ obj.document.url }}">
                        <font color="#000000">{{ obj.document.name }}</a>
                    </font>
                    <br><small>{{ obj.created }}</small></li><br> {% else %}
                <li class="text-left list-group-item">
                    <font color="#1ABC9C">{{ obj.userUpload }}</font><br>
                    <a href="{{ obj.document.url }}">
                        <font color="#000000">{{ obj.document.name }}</a>
                    </font>
                    <br><small>{{ obj.created }}</small></li><br> {% endif %} {% endfor %}


                <script>
                    var chatlist = document.getElementById('msg-list-div');
                    //chatlist.scrollTop = chatlist.scrollHeight;
                </script>
            </ul>
            <div><a class="btn btn-warning" value="Upload File" href="{% url 'blog:uploads' %}">Upload File</a></div>


        </div>
    </div>
    <div id="form-input" style="height: 100px;">


        <form id="chat-form" method="POST" action="{%url 'blog:post' %}">
            {% csrf_token %}
            <div id="chat-bottom" class="input-group">
                <input type="text" id="chat-msg" name="chat-msg" class="form-control" />
                <span class="input-group-btn">
                    <input class="btn btn-left" id="send" type="submit" value="Send"/>
                </span>
            </div>

        </form>

    </div>

    <script src="{% static 'js/chat.js' %}"></script>
    <script src="{% static 'js/jquery.cookie.js' %}"></script>

</div>
{% endblock content %}

templates/blog/Inscription.html
{% extends "base.html" %}{% load staticfiles %} {% block title %}
<title>S'inscrire</title>{% endblock title %}{% block content %}
<div class="container">

    <div class="color-line"></div>
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="back-link back-backend">
                    <a href="index.html" class="btn btn-primary">Back to Dashboard</a>
                </div>
            </div>
        </div>
    </div>
    {% if messages %}
    <ul>
        {% for message in messages %}
        <li>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}

    <h1>Create account - The Great Django Blog</h1>

    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12"></div>
            <div class="col-md-6 col-md-6 col-sm-6 col-xs-12">
                <div class="text-center custom-login">
                    <h3>Registration</h3>
                    <p>Admin template with very clean and aesthetic style prepared for your next app. </p>
                </div>
                <div class="hpanel">
                    <div class="panel-body">
                        <form id="register" method="POST" role="form" action="{%url 'blog:register' %}">
                            {% csrf_token %}
                            <div class="row">
                                <div class="form-group col-lg-12">
                                    <label class="control-label" name="username" for="username">Username</label>
                                    <input type="text" placeholder="example@gmail.com" title="Please enter you username" required="" value="{{Users.username}}" name="username" id="username" class="form-control">

                                </div>
                                <div class="form-group col-lg-6">
                                    <label class="control-label" name="password" for="password">Password</label>
                                    <input type="password" title="Please enter your password" placeholder="******" required="" value="{{Users.password}}" name="password" id="password" class="form-control">

                                </div>
                                <div class="form-group col-lg-6">
                                    <label>Repeat Password</label>
                                    <input type="password" title="Please enter your password" placeholder="******" required="" value="{{Users.password}}" name="password" id="password" class="form-control">
                                </div>
                                <div class="checkbox col-lg-12">
                                    <input type="checkbox" class="i-checks" checked> Sigh up for our newsletter
                                </div>
                            </div>
                            <div class="text-center">
                                <button href="{% url 'blog:login' %}" class="btn btn-success loginbtn" id="send" type="submit" name="inscription">Register</button>
                                <button class="btn btn-default">Cancel</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12"></div>
        </div>
    </div>
    {% endblock content %}

templates/blog/Interventi.html
{% extends "base1.html" %}{% load staticfiles %} {% block title %}
<title>Liste des Bureau</title>{% endblock title %}{% block content %}
<div class="container">
    <br />
    <br />
    <div class="clearfix"></div>

    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="tab-content-details shadow-reset">
                <h1> Les Interventions de l'informaticien</h1>
                <h2>A prpos des interventions qu' effectuer notre information suite aux pannes signaler par nos agents. </h2>
                <p>These are the Custom Animate Modals Bootstrap. Using animate bounce, flash, pulse, rubberBand, shake, swing, tada, wobble, jello, bounceIn, bounceInDown, bounceInLeft, bounceInRight, bounceInUp, fadeIn, fadeInDown, fadeInDownBig, fadeInLeft,
                    fadeInLeftBig, fadeInRight, fadeInRightBig, fadeInUp, fadeInUpBig, flipInX, flipInY, lightSpeedIn, rotateIn, rotateInDownLeft, rotateInDownRight, rotateInUpLeft, rotateInUpRight, rollIn, zoomIn, zoomInDown, zoomInLeft, zoomInRight,
                    zoomInUp etc.</p>
            </div>
        </div>
    </div>
    <div class="col-md-3 col-sm-3  offset-md-5">
        <!-- <button type="button" class="btn btn-primary">Cancel</button>

        <button type="submit" class="btn btn-success">Submit</button> -->
    </div>


    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="tab-content-details shadow-reset">
                <a href="{% url 'intervention:intervention_detail' %}" class="btn btn-primary waves-effect waves-light m-r-10"> Interventions </a>
                <a href="{% url 'intervention:panne_detail' %}" class="btn btn-primary waves-effect waves-light m-r-10"> Pannes </a>
                <a href="{% url 'intervention:type_panne_detail' %}" class="btn btn-primary waves-effect waves-light m-r-10"> Types Pannes </a>

            </div>
        </div>
    </div>
</div>
{% endblock content %}

templates/blog/Parcs.html
{% extends "base1.html" %}{% load staticfiles %} {% block title %}
<title>Liste des Bureau</title>{% endblock title %}{% block content %}
<div class="container">
    <br />
    <br />
    <div class="clearfix"></div>

    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="tab-content-details shadow-reset">
                <h1> Le Parc Informatique</h1>
                <h2>A prpos de notre parc, ou nous avons nos Materiels, Types de materiel </h2>
                <p>These are the Custom Animate Modals Bootstrap. Using animate bounce, flash, pulse, rubberBand, shake, swing, tada, wobble, jello, bounceIn, bounceInDown, bounceInLeft, bounceInRight, bounceInUp, fadeIn, fadeInDown, fadeInDownBig, fadeInLeft,
                    fadeInLeftBig, fadeInRight, fadeInRightBig, fadeInUp, fadeInUpBig, flipInX, flipInY, lightSpeedIn, rotateIn, rotateInDownLeft, rotateInDownRight, rotateInUpLeft, rotateInUpRight, rollIn, zoomIn, zoomInDown, zoomInLeft, zoomInRight,
                    zoomInUp etc.</p>
            </div>
        </div>
    </div>
    <div class="col-md-3 col-sm-3  offset-md-5">
        <!-- <button type="button" class="btn btn-primary">Cancel</button>

        <button type="submit" class="btn btn-success">Submit</button> -->
    </div>


    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="tab-content-details shadow-reset">
                <a href="{% url 'parc:materiel_detail' %}" class="btn btn-primary waves-effect waves-light m-r-10"> Materiel </a>
                <a href="{% url 'parc:types_materiel_detail' %}" class="btn btn-primary waves-effect waves-light m-r-10"> Types Materiel </a>

            </div>
        </div>
    </div>
</div>
{% endblock content %}

templates/blog/Projet.html
{% extends "base.html" %}{% load staticfiles %} {% block title %}
<title>Projets</title>{% endblock title %}{% block content %}
<div class="container">

</div>
{% endblock content %}

templates/blog/Services.html
{% extends "base1.html" %}{% load staticfiles %} {% block title %}
<title>Liste des Bureau</title>{% endblock title %}{% block content %}
<div class="container">
    <br />
    <br />
    <div class="clearfix"></div>

    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="tab-content-details shadow-reset">
                <h1> Nos Services</h1>
                <h2>A prpos de nos services, nos departements, bureau et intervenant </h2>
                <p>These are the Custom Animate Modals Bootstrap. Using animate bounce, flash, pulse, rubberBand, shake, swing, tada, wobble, jello, bounceIn, bounceInDown, bounceInLeft, bounceInRight, bounceInUp, fadeIn, fadeInDown, fadeInDownBig, fadeInLeft,
                    fadeInLeftBig, fadeInRight, fadeInRightBig, fadeInUp, fadeInUpBig, flipInX, flipInY, lightSpeedIn, rotateIn, rotateInDownLeft, rotateInDownRight, rotateInUpLeft, rotateInUpRight, rollIn, zoomIn, zoomInDown, zoomInLeft, zoomInRight,
                    zoomInUp etc.</p>
            </div>
        </div>
    </div>
    <div class="col-md-3 col-sm-3  offset-md-5">
        <!-- <button type="button" class="btn btn-primary">Cancel</button>

        <button type="submit" class="btn btn-success">Submit</button> -->
    </div>


    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="tab-content-details shadow-reset">
                <a href="{% url 'service:bureau_detail' %}" class="btn btn-primary waves-effect waves-light m-r-10"> Bureau </a>
                <a href="{% url 'service:departement_detail' %}" class="btn btn-primary waves-effect waves-light m-r-10"> Departement </a>
                <a href="{% url 'service:intervenant_detail' %}" class="btn btn-primary waves-effect waves-light m-r-10"> Intervenant </a>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

templates/blog/Signup.html
{% extends "base.html" %}{% load staticfiles %} {% block title %}
<title>Contact</title>{% endblock title %}{% block content %}
<div class="container">
    h2>Sign up Form</h2>
    <form method="post" role="form" action="{%url 'userprofile:signup' %}">
        {% csrf_token %}
        <input type="text" name="username" placeholder="Utilisateur">
        <input type="password" name="password" placeholder="Mot de passe">
        <input type="submit" value="login" />
    </form>
</div>

{% endblock content %}